baseURL = 'https://jajerje.fun'
title = 'Feed The Leader'

timeZone = 'Europe/Madrid'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true

buildFuture = true


[languages]
  
  [languages.es]
    disabled = false
    contentDir = 'content/es'
    languageCode = 'es-es'
    languageName = 'Español'
    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "home"
        name = "Inicio"
        url = "/es"
        weight = 10

      [[languages.es.menu.main]]
        identifier = "principles"
        name = "Ideario"
        url = "/es/principles"
        weight = 20

      [[languages.es.menu.main]]
        identifier = "download"
        name = "¡Descárgame!"
        url = "/es/download"
        weight = 30

      [[languages.es.menu.main]]
        identifier = "contact"
        name = "Contacto"
        url = "/es/contact"
        weight = 40

      [[languages.es.menu.main]]
      identifier = "whoarewe"
      name = "¿Quiénes somos?"
      url = "/es/whoarewe"
      weight = 50

    [languages.es.params]
      description = 'Oda al líder'

[params]
  [params.social]
    twitter = 'FeedTheLeader'
    title = 'Feed The Leader - JAJERJE studios'
    description = 'Oda al líder.'
    image = 'https://jajerje.fun/favicon.ico'
