baseURL = 'http:/84.235.237.105/'
title = 'DAJER'

timeZone = 'Europe/Madrid'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true

buildFuture = true


[languages]
  
  [languages.es]
    disabled = false
    contentDir = 'content/es'
    languageCode = 'es-es'
    languageName = 'Español'
    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "home"
        name = "Inicio"
        url = "/es"
        weight = 10

      [[languages.es.menu.main]]
        identifier = "reservoir"
        name = "Embalses"
        url = "/es/reservoir"
        weight = 20

      [[languages.es.menu.main]]
        identifier = "map"
        name = "Mapa interactivo"
        url = "/es/map"
        weight = 30

      [[languages.es.menu.main]]
        identifier = "analysis"
        name = "Análisis"
        url = "/es/analysis"
        weight = 40

        [[languages.es.menu.main]]
        identifier = "contact"
        name = "Contacto"
        url = "/es/contact"
        weight = 50

        [[languages.es.menu.main]]
        identifier = "whoarewe"
        name = "¿Quiénes somos?"
        url = "/es/whoarewe"
        weight = 60

    [languages.es.params]
      description = 'Get the water going (GTWG)'

[params]
  [params.social]
    twitter = 'DAJER'
    title = 'DAJER'
    description = 'A sustainable approach to water management '
    image = 'https://jajerje.fun/favicon.ico'
